name: storage
description: Secure storage adapter
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.2.0
  meta: ^1.18.0

  # packages
  shared_kernel:
    path: ../shared_kernel
