name: storage
description: Secure storage adapter
publish_to: none

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 10.0.0
  meta: ^1.17.0
  shared_kernel:
    path: ../shared_kernel
