name: bitcoin_wallet
description: "Demo Bitcoin wallet with a local Bitcoin Core regtest node."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

workspace:
  - packages/address
  - packages/bitcoin_node
  - packages/keys
  - packages/rpc_client
  - packages/shared_kernel
  - packages/storage
  - packages/ui_kit
  - packages/wallet

dependencies:
  address:
    path: packages/address
  bitcoin_node:
    path: packages/bitcoin_node
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  keys:
    path: packages/keys
  rpc_client:
    path: packages/rpc_client
  shared_kernel:
    path: packages/shared_kernel
  storage:
    path: packages/storage
  ui_kit:
    path: packages/ui_kit
  wallet:
    path: packages/wallet

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
