name: bitcoin_wallet
description: "Demo Bitcoin wallet with a local Bitcoin Core regtest node."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

workspace:
  - packages/action_bloc
  - packages/bitcoin_node
  - packages/keys
  - packages/rpc_client
  - packages/shared_kernel
  - packages/storage
  - packages/transaction
  - packages/ui_kit
  - packages/wallet

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 9.1.1
  qr_flutter: 4.1.0

  # packages
  action_bloc:
    path: packages/action_bloc
  bitcoin_node:
    path: packages/bitcoin_node
  keys:
    path: packages/keys
  rpc_client:
    path: packages/rpc_client
  shared_kernel:
    path: packages/shared_kernel
  storage:
    path: packages/storage
  transaction:
    path: packages/transaction
  ui_kit:
    path: packages/ui_kit
  wallet:
    path: packages/wallet

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
