name: wallet
description: Wallet module — entities, repository, use cases
publish_to: none

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  keys:
    path: ../keys
  shared_kernel:
    path: ../shared_kernel
  uuid: 4.5.3

dev_dependencies:
  test: 1.30.0
