import 'package:transaction/src/domain/value_object/coin_candidate.dart';
import 'package:transaction/src/domain/value_object/coin_selection_strategy_result.dart';

/// Immutable result of [PrepareNodeSendUseCase].
///
/// Holds the UTXO candidates and coin-selection results for all strategies so
/// the UI can show a comparison table before the user confirms the send.
final class NodeSendPreparation {
  final List<CoinCandidate> candidates;

  /// Ordered list of strategy results. Each entry carries name, isStochastic,
  /// and the [CoinSelectionResult] for the comparison table.
  final List<CoinSelectionStrategyResult> strategies;

  /// Change address generated by Bitcoin Core for this preparation.
  final String changeAddress;

  const NodeSendPreparation({
    required this.candidates,
    required this.strategies,
    required this.changeAddress,
  });
}
